=== trivago/express-booking-selfconnect-api/schemas/booking-submit-request.json
{
  "title": "Booking Submit Request",
  "type": "object",
  "$schema": "http://json-schema.org/schema#",
  "description": "Schema of an booking submit request.",
  "required": [
    "checkin_date",
    "checkout_date",
    "partner_reference",
    "customer",
    "rooms",
    "final_price_at_booking",
    "final_price_at_checkout",
    "partner_data"
  ],
  "properties": {
    "rooms": {
      "minItems": 1,
      "description": "An array of rooms to be booked.",
      "type": "array",
      "items": {
        "$ref": "room-stay.json"
      }
    },
    "checkin_date": {
      "description": "The user's check-in date in YYYY-MM-DD.\nThe check-in date of the traveler.",
      "type": "string",
      "format": "date",
      "example": "2019-01-01"
    },
    "customer": {
      "$ref": "customer.json"
    },
    "checkout_date": {
      "description": "The user's check-out date in YYYY-MM-DD.\nThe check-out date of the traveler.",
      "type": "string",
      "format": "date",
      "example": "2019-01-02"
    },
    "partner_reference": {
      "description": "Advertiser's unique hotel id.\nPartner hotel id.",
      "type": "string",
      "example": "1"
    },
    "partner_data": {
      "$ref": "partner-data.json"
    },
    "payment": {
      "description": "Defines the selected payment method of the user.",
      "$ref": "payment.json"
    },
    "final_price_at_booking": {
      "description": "An object containing the entire price to be paid at time of booking, including taxes and fees.\\nThis will be used to validate the line items.",
      "$ref": "price.json",
      "example": {
        "currency": "USD",
        "amount": 100
      }
    },
    "api_version": {
      "description": "Version of the API used.",
      "type": "integer",
      "example": 1
    },
    "reference_id": {
      "description": "trivago identifier for the booking session. Please consider that this id might not be unique and should not be\ntreated as a \"confirmation\" id. Identifier for the booking session",
      "type": "string",
      "example": "692e8acc-d1d9-45dc-b50f-e7b824f3306f"
    },
    "tracking_data": {
      "description": "Enables advertisers to receive specific information for tracking purpose. Fields supported here can be static fields as given by advertiser or can be dynamic fields as supported for tracking pixel which can be fired from express landing page. Refer here for tracking parameters supported from trivago side at submit e.g:\n\"tracking_data\": {\n\"actor\": \"trivago\",\n\"tracking_id\": \"3125354\"\n}",
      "example": {
        "advLink": "http://advertiser-site.com/hoteladlon/Executive_Brilliant_Doppelzimmer?start_date=2016-12-28&end_date=2016-12-29",
        "actor": "trivago"
      }
    },
    "payment_method": {
      "description": "An object containing the credit card details for payment of the reservation.",
      "$ref": "booking-submit-request-payment-method.json"
    },
    "final_price_at_checkout": {
      "description": "An object containing the entire price to be paid at time of stay, including taxes and fees.\\nThis will be used to validate the line items. If the full price is paid at the time of booking,\\nthis element must still be included, with an amount of 0 or 0.00.",
      "$ref": "price.json",
      "example": {
        "currency": "USD",
        "amount": 5
      }
    },
    "ip_address": {
      "description": "Sending IP address.",
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== trivago/express-booking-selfconnect-api/examples/booking-submit/request.json
{
  "checkin_date": "2016-01-25",
  "checkout_date": "2016-01-26",
  "partner_reference": "abc123",
  "reference_id": "692e8acc-d1d9-45dc-b50f-e7b824f3306f",
  "partner_data": {
    "identifier_for_something": "9614b191-9e1b-4b7d-9cbc-5b9204ac2a2a"
  },
  "tracking_data": {
    "actor": "trivago",
    "advLink": "http://advertiser-site.com/hoteladlon/Executive_Brilliant_Doppelzimmer?start_date=2016-12-28&end_date=2016-12-29"
  },
  "payment": {
    "method": {
      "code": "PaymentCard",
      "options": [
        {
          "code": "MasterCard",
          "fee": {
            "amount": 0.0,
            "currency": "USD"
          }
        }
      ]
    },
    "parameters": {
      "card_number": "6011111111111117",
      "cardholder_name": "Christopher Palmer",
      "expiration_month": "09",
      "expiration_year": "2025",
      "cvv": "507",
      "callback_success": "",
      "callback_cancel": "",
      "callback_error": "",
      "type": "PaymentCard"
    },
    "billing_address": {
      "address1": "12 Johnson Junction",
      "city": "Santa Cruz",
      "state": "Maryland",
      "postal_code": "97897",
      "country": "US"
    }
  },
  "customer": {
    "first_name": "Christopher",
    "last_name": "Palmer",
    "phone_number": "9-(590)311-9256",
    "email": "john@doe.com",
    "country": "US"
  },
  "rooms": [
    {
      "party": {
        "adults": 2,
        "children": [
          1
        ]
      },
      "traveler_first_name": "Christopher",
      "traveler_last_name": "Palmer"
    }
  ],
  "final_price_at_booking": {
    "amount": 100.0,
    "currency": "USD"
  },
  "final_price_at_checkout": {
    "amount": 5.00,
    "currency": "USD"
  }
}
