=== trivago/express-booking-selfconnect-api/schemas/booking-availability-response-success.json
{
  "type": "object",
  "title": "Booking Availability Ok",
  "$schema": "http://json-schema.org/schema#",
  "required": [
    "api_version",
    "hotel_id",
    "start_date",
    "end_date",
    "party",
    "lang",
    "user_country",
    "room_types_array",
    "customer_support"
  ],
  "properties": {
    "terms_and_conditions_url": {
      "description": "Link to the advertiser's terms and conditions page.",
      "type": "string"
    },
    "hotel_id": {
      "description": "Echo the item_id (not partner_reference) provided by trivago in the corresponding request.",
      "type": "integer"
    },
    "lang": {
      "description": "Language code (see Supported Languages)[http://developer.trivago.com/expressbooking/supported-languages.html], which identifies the corresponding language and POS.",
      "example": "en_US",
      "type": "string"
    },
    "end_date": {
      "description": "The user's check-out date in YYYY-MM-DD",
      "example": "2019-01-02",
      "format": "date",
      "type": "string"
    },
    "query_key": {
      "description": "Query Key",
      "deprecated": true,
      "type": "string"
    },
    "currency": {
      "description": "ISO 4217 currency code. All prices, taxes, fees, and discount amounts should be returned in this requested currency.",
      "example": "USD",
      "type": "string"
    },
    "terms_and_conditions": {
      "description": "General terms and conditions.\nText field.\nLength limit of 1000 characters.",
      "type": "string"
    },
    "customer_support": {
      "$ref": "customer-support.json"
    },
    "payment_policy": {
      "description": "Describes how the advertiser will use the credit card information, e.g. charged immediately or hold.\nText field.\nLength limit of 1000 characters.",
      "type": "string"
    },
    "start_date": {
      "description": "The user's check-in date in YYYY-MM-DD",
      "example": "2019-01-01",
      "format": "date",
      "type": "string"
    },
    "errors": {
      "description": "Array of errors",
      "items": {
        "$ref": "error.json"
      },
      "type": "array"
    },
    "hotel_details": {
      "$ref": "hotel-details.json"
    },
    "room_types_array": {
      "description": "An array of objects detailing the different kinds of rooms that are available for the entire party.\nThe short description must be unique for each room type available in the hotel.",
      "items": {
        "$ref": "room-type.json"
      },
      "type": "array"
    },
    "other_policy": {
      "description": "Miscellaneous policies\nText field.\nLength limit of 1000 characters.",
      "type": "string"
    },
    "user_country": {
      "description": "ISO 3166-1 alpha-2 country code corresponding to the user making this request.",
      "example": "US",
      "type": "string"
    },
    "api_version": {
      "description": "Version of the API used.",
      "example": 1,
      "type": "integer"
    },
    "device_type": {
      "description": "Device Type",
      "deprecated": true,
      "type": "string"
    },
    "party": {
      "description": "Array of JSON objects inlcuding number of adults and children requested.\nEach party object represents the occupation for a separate room.\nFor example, \"party\":[{\"adults\": 3}] is a request for one room that accommodates three adults,\nor \"party\":[{\"adults\": 2},{\"adults\": 2, \"children\": [11,8]}] is a request for one room for two adults\nand one room for two adults and two children aged 11 and 8.",
      "items": {
        "$ref": "party.json"
      },
      "minItems": 1,
      "type": "array"
    },
    "accepted_credit_cards": {
      "description": "Accepted Credit Cards",
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "description": "Schema Booking availability when response is OK"
}

=== trivago/express-booking-selfconnect-api/examples/booking-availability/response_no_availabilities.json
{
  "api_version": 1,
  "hotel_id": 730099,
  "start_date": "2016-01-25",
  "end_date": "2016-01-26",
  "party": [
    {
      "adults": 2,
      "children": [
        1
      ]
    }
  ],
  "lang": "en_US",
  "user_country": "US",
  "room_types_array": [],
  "customer_support": {
    "phone_numbers": [
      {
        "contact": "123456780",
        "description": "support phone"
      }
    ],
    "emails": [
      {
        "contact": "support@advertiser.com",
        "description": "support email"
      }
    ],
    "urls": [
      {
        "contact": "support@advertiser.com",
        "description": "support website"
      }
    ]
  }
}

=== trivago/express-booking-selfconnect-api/examples/booking-availability/response_with_installment.json
{
  "api_version": 1,
  "hotel_id": 730099,
  "start_date": "2016-01-25",
  "end_date": "2016-01-30",
  "party": [
    {
      "adults": 2,
      "children": [
        1
      ]
    }
  ],
  "lang": "en_US",
  "user_country": "US",
  "room_types_array": [
    {
      "name": "Double Room, 1 King Bed",
      "final_price_at_booking": {
        "amount": 100,
        "currency": "USD"
      },
      "final_price_at_checkout": {
        "amount": 5,
        "currency": "USD"
      },
      "description": "Air-conditioned room with a minibar, desk and private bathroom.",
      "rooms_available": 4,
      "partner_data": {
        "identifier_for_something": "9614b191-9e1b-4b7d-9cbc-5b9204ac2a2a"
      },
      "rate_key": "0fd6eca9-9c33-4978-b9bc-b3f3d60f6205",
      "room_type": "STANDARD",
      "occupancy": {
        "standard_persons": 2,
        "max_persons": 3,
        "max_adults": 2,
        "max_children": 2,
        "max_children_age": 16
      },
      "room_group": {
        "code": "e5db04fa67d6",
        "name": "Cozy Double Room",
        "description": "Air-conditioned room with a minibar, desk and private bathroom."
      },
      "line_items": [
        {
          "price": {
            "amount": 100,
            "currency": "USD"
          },
          "type": "net_rate",
          "paid_at_checkout": false,
          "description": "base price"
        },
        {
          "price": {
            "amount": 5,
            "currency": "USD"
          },
          "type": "city_tax",
          "paid_at_checkout": true,
          "description": "city tax"
        }
      ],
      "amenities": [
        "free bottle of water",
        "air condition"
      ],
      "value_adds": [
        "FREE_BREAKFAST",
        "FREE_INTERNET",
        "FREE_PARKING"
      ],
      "payment_methods": [
        {
          "code": "PaymentCard",
          "options": [
            {
              "code": "MasterCard",
              "fee": {
                "amount": 0.0,
                "currency": "USD"
              }
            },
            {
              "code": "Visa",
              "fee": {
                "amount": 2.77,
                "currency": "USD"
              },
              "installments": [
                {
                  "id": "1",
                  "swift_code": "ABC",
                  "number": 8,
                  "frequency": "M",
                  "installment_amount": {
                    "amount": 40.0,
                    "currency": "USD"
                  },
                  "initial_deposit": {
                    "amount": 80.0,
                    "currency": "USD"
                  },
                  "last_amount": {
                    "amount": 50.0,
                    "currency": "USD"
                  },
                  "extra_fee": {
                    "amount": 50.0,
                    "currency": "USD"
                  },
                  "discount": {
                    "amount": 10.0,
                    "currency": "USD"
                  },
                  "interest_charge": 30.0,
                  "first_installment": 0
                },
                {
                  "id": "2",
                  "number": 6,
                  "frequency": "M",
                  "installment_amount": {
                    "amount": 50.0,
                    "currency": "USD"
                  }
                }
              ]
            }
          ]
        },
        {
          "code": "ExternalProvider",
          "options": [
            {
              "code": "Paypal",
              "fee": {
                "amount": 0.0,
                "currency": "USD"
              }
            }
          ]
        },
        {
          "code": "BankAccount",
          "options": [
            {
              "code": "DirectDebit",
              "fee": {
                "amount": 0,
                "currency": "GBP"
              }
            }
          ]
        },
        {
          "code": "ManualPayment",
          "options": [
            {
              "code": "BankTransfer",
              "fee": {
                "amount": 0,
                "currency": "GBP"
              }
            }
          ]
        }
      ],
      "photos": [
        {
          "url": "https://trv-companypages.s3-eu-central-1.amazonaws.com/wp-content/uploads/sites/2/2015/07/trivago_logo_twitter-1024x512.png",
          "caption": "Trivago logo",
          "width": 1024,
          "height": 512
        }
      ],
      "cancellation": {
        "policy": "free text",
        "penalties": [
          {
            "fee": {
              "amount": 20.0,
              "currency": "USD"
            }
          },
          {
            "from": "2016-01-18T16:00:00+0000",
            "fee": {
              "amount": 100.0,
              "currency": "USD"
            }
          }
        ]
      },
      "promotions": [
        {
          "type": "MOBILE_ONLY",
          "description": "...",
          "discount": {
            "percentage": 25,
            "total": {
              "amount": 25,
              "currency": "USD"
            }
          }
        }
      ]
    }
  ],
  "hotel_details": {
    "name": "Some Awesome Hotel",
    "address1": "52977 Ismael Bridge",
    "city": "South Maurice",
    "state": "NY",
    "postal_code": "01234",
    "country": "USA",
    "latitude": -61.7414,
    "longitude": -174.122,
    "phone": "(509) 711-6896",
    "url": "http://www.hotel-site.com/welcome",
    "amenities": [
      "RESTAURANT",
      "NON_SMOKING",
      "FREE_PARKING"
    ],
    "photos": [
      {
        "url": "https://trv-companypages.s3-eu-central-1.amazonaws.com/wp-content/uploads/sites/2/2015/07/trivago_logo_twitter-1024x512.png",
        "caption": "Trivago logo",
        "width": 1024,
        "height": 512
      }
    ],
    "checkinout_policy": "check-in from 3pm and check-out till 12am"
  },
  "customer_support": {
    "phone_numbers": [
      {
        "contact": "1-153-072-9237 x6907",
        "description": "Tempora iure sit accusamus et cupiditate autem reiciendis iusto."
      }
    ],
    "emails": [
      {
        "contact": "Roxane.McKenzie@gmail.com",
        "description": "Aspernatur reiciendis quis at qui asperiores."
      }
    ],
    "urls": [
      {
        "contact": "http://kasey.info",
        "description": "Maiores enim cupiditate deserunt ut."
      }
    ]
  }
}
